- .github/workflows/test.yml
- action.yml
- dist/post_run/index.js
- dist/run/index.js
- src/run.ts
> Add working-directory support

- .github/workflows/test.yml
- README.md
- dist/post_run/index.js
- dist/run/index.js
- package-lock.json
- package.json
- src/cache.ts
- src/constants.ts
- src/utils/actionUtils.ts
Fixes #14 
https://github.com/sayboras/golangci-lint-action/runs/698981324?check_suite_focus=true
<details>
<summary>Restore cache</summary>
```
prepare environment
Finding needed golangci-lint version...
Setup go stable version spec 1
A version satisfying 1 not found locally, attempting to download ...
Requested golangci-lint 'v1.26', using 'v1.26.0', calculation took 286ms
Installing golangci-lint v1.26.0...
Downloading https://github.com/golangci/golangci-lint/releases/download/v1.26.0/golangci-lint-1.26.0-linux-amd64.tar.gz ...
Downloading from https://storage.googleapis.com/golang/go1.14.3.linux-amd64.tar.gz
Cache Size: ~0 MB (28191 B)
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/55990ecc-a52b-42fb-928d-26f56fe0343f/cache.tzst -P -C …
```
> Replace forked cache by official npm

- README.md
Added a matrix to show how to do multi-os lint builds.  This is specifically needed if you have files like `_darwin.go` or `_windows.go`, etc.  If you don't lint on that specific OS, then those files will NOT be linted.
I also added a note about `.gitattributes` needing to have the line endings correctly checked out, otherwise linting will fail for formatting as well.
> Add instructions for multi-os linting

- README.md
Recently GitHub switched default branch name to `main` from `master`, this affects new repositories.
This PR updates examples in README to use both `master` and `main`.
> Add main to list of branches in README example

- README.md
- ~_it's_~ = it _is_ (or _has_)
- **its** - possessive pronoun of _it_ (something belongs to _it_)
See https://www.grammarly.com/blog/possessive-pronouns/: _A Common Mistake: Its vs. It’s_
The same applies for the repository description:
> Fix a typo in README.md (it's->its)

- README.md
- action.yml
- dist/post_run/index.js
- dist/run/index.js
- src/cache.ts
Fix #153.
- Add option to skip caching the Go package directory (`~/go/pkg`).
- Add option to skip caching the Go build directory (`~/.cache/go-build`).
- Update README to mention new options.
> Add options to skip caching of folders.

- README.md
#98 was closed by #101, but the README still says that only a major-minor version is accepted. It also says that this field is required, but `action.yml` says otherwise. Copy the description from `action.yml` into the README for consistency.
> Update "version" config in README example

- dist/post_run/index.js
- dist/run/index.js
- src/version.ts
This first implementation is a very naive approach: Assuming that the `go.mod` file is residing in the repository root (and thus the current working directory I guess).
If the `version` input is not set, the `go.mod` file is loaded, the version extracted from the `github.com/golangci/golangci-lint v1.32.0` line using a regex.
Closes #106.
> Try to get version from go.mod file

- dist/post_run/index.js
- dist/run/index.js
- src/run.ts
The current implementation mangles the contents of `userArgsNames` and prevents the successful checks that follow (preventing setting `out-format` and any of the `new-` parameters.  This fix extracts the names with a regex without mangling them.  The original iterative extraction looked creative and mildly elegant, but in testing, expanding it to not mangle the names made it less elegant, so using a `regex` and doing it in one go without iterating the array seemed like a simpler and more straight-forward approach.
Resolves: #199
**Note:** It looks like this bug has been in here for about 10 months (https://github.com/golangci/golangci-lint-action/commit/10cbc929b3868f44d02dc99a3368f81237ca356a), fixing this may break existing deployments.  Especially considering how I just suggested …
> Extract and don't mangle User Args.

- README.md
- action.yml
- dist/post_run/index.js
- dist/run/index.js
- src/cache.ts
Fixes #232 to avoid unnecessary activities and warnings on GHES, where caching is not supported.
> Allow to disable caching completely

- README.md
Currently，v3 has released, so could we update all of this version to v3 in README ?
> docs: update version to v3

- README.md
README for v3 is currently almost the same as v2 (#450), which may confuse some developers.
- #442
- #448
This PR updates examples of using setup-go@v3 to configure a golang environment that works properly.
https://github.com/actions/setup-go#supported-version-syntax
> modify examples using setup-go

- dist/post_run/index.js
- dist/run/index.js
- src/cache.ts
The cache key includes a sequence number that rotates every 7 days but because we are also using the base `golangci-lint.cache` as a restore key, the new cache will always be seeded with the full contents of the old cache.
In particular for the go module cache, this leads to an ever increasing number of cached packages that never get pruned.
This commit updates it so we stop using `golangci-lint.cache` as a restore key, which will force a build from an empty cache once every 7 days.
Fixes #465
> Expire cache periodically to avoid unbounded size

- action.yml
> fix: optional props not required

- dist/post_run/index.js
- dist/run/index.js
- src/cache.ts
Right now the `go.mod` is used as the cache key is expected to always be at the root of the repository. This works for most repositories but when users have a mono repo and supply a `working-directory` the caching keys should use that as the root directory instead
This PR fixes #479 
Also wanted to add that we use golangci extensively in in [CloudQuery](https://github.com/cloudquery/cloudquery) and this would definitely help us avoid hitting timeouts...
> Support Caching in Mono Repo 

- README.md
I recently came across a bug (https://github.com/golangci/golangci-lint-action/issues/669) where specifying `go-version: '1.20'` used Go 1.2, not 1.20. It was not clear from the readme that to avoid this, the Go version should be written inside single quotes (as per this comment: https://github.com/actions/setup-go/issues/326#issuecomment-1415719692) but the single quotes are missing from the example in this repository.  This PR fixes this.
> doc: add quote aroung go version

- .github/workflows/test.yml
- README.md
setup-go v4 uses cache automatically, which conflicts with golangci-lint's cache.
This is not a fix, rather a documentation and build setup update, in 2 separated commits so they might be cherry-picked :)
refs #677
> docs/build: update to setup-go@v4

- README.md
fix followings
* `platform-arch` is not used for key
* https://github.com/golangci/golangci-lint-action/blob/92ba55cf0d79a9feb999e9bcef95c952bbbe545a/src/cache.ts#L57
* `golangci-lint.cache-` is not used as restore key
* (if use `golangci-lint.cache-`, cache will not purged by `internal_number`)
> fix invalid docs about cache key

- README.md
Thanks for the excellent work, it is really helpful. And there is a useful example of custom configuration, it can reduce the users' confusion. It was mentioned at  https://github.com/golangci/golangci-lint-action/issues/26 So, please consider merging this PR.
> doc: Add custom configuration file path to args

- .github/workflows/test.yml
- README.md
- action.yml
- dist/post_run/index.js
- dist/run/index.js
- src/install.ts
- src/run.ts
- src/version.ts
Allow installing golangci-lint by using `go install`.
Fixes #540
Fixes #201
Closes #676
Related to #690
> feat: add install-mode

- dist/post_run/index.js
- dist/run/index.js
- src/run.ts
This PR adds support for `--out-format` as supported arguments.
when not set, behavior is unchanged and the `github-actions` format is added.
When set, and `github-actions` is not given, it is added as the first output, otherwise, it is not added.
Any other provided format is preserved.
Fixes #458
Fixes #362
Closes #613
> feat: support out-format as args

- dist/post_run/index.js
- dist/run/index.js
- src/run.ts
https://github.com/golangci/golangci-lint-action/pull/769#issuecomment-1586892702
ping @jrehwaldt 
[Playground](https://www.typescriptlang.org/play?#code/DYUwLgBArgziBOBBeBzGEC8EBEBaXA9lACq4BmB8AtgIZgYUET5FjmW30BGN8zuAcQJNsAKADGBAHYxINACbyQ85GgBcEWfACWUlAG0AupghHRE6bOhwkqGABltVrLASqYoiF4gA6MDqoACgBKT28fGAAHYG0wQIB6AB0YAGp40O9fMm1gMARAwN4UYMwAPggiiLBeMBgAdViAC0CAA1wW4Izw2kiCopKMcsr4EGiacRAEgD1cNIAaCBaOrq8fHr7UAaHUCOjYhIxAnwAqYPiFgCZOsNWegB59LV0UBae9Q1KC-QBrEABPBYANxowCgIEMW1Mvz+fgI9gIAHcEABhGhwEJAkFgiAAfhxOGwEPMkhkkFctjQAFkaJETFIQAiINTInc3i9NP5np9ye5HLJQiSrDzUAA5GhUEDoLD0xkAZXArM5em5Nl5TjAaxpX2hELKEGh1wspIgFGodClEECwqpNJ8KHAgWwrHYZrA2BKAB8PQSVr5OUFfbsYnFsHN3Tcsjk8vACmRIWQfKA9GBGhBygAGQPZXL5QJxvUAQgTshq9SarRQTSgXFw4zA2ksywjPhJ4jojsrKertfE9cs4cyPgAVgRdI6w6FRAolCo7D5IrBmm1CFA2KbOBgACQAb3X5oAvh …
> fix: out-format

- README.md
Some improvements in `How to use` section from README.md to make the documentation more perfect!
> docs: improve `How to use` section in README.md

- .github/workflows/codeql.yaml
- action.yml
Node 16 reaches the [end of life soon on 11 Sep 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol). This PR updates the default runtime to node20 (Node 20). I have also bumped the actions/checkout version to v4 for the same.
Related issue:
https://github.com/actions/runner/pull/2732
----
A major version bump might be needed after the PRs merge.
> chore: bump to use node20 runtime, actions/checkout to v4

- README.md
Annotations seem to require permissions now
> docs: update section about GitHub Annotations

- README.md
- `actions/checkout@v3` -> `actions/checkout@v4`
- `actions/setup-go@v4` -> `actions/setup-go@v5`
- `golangci/golangci-lint-action@v3` -> `golangci/golangci-lint-action@v4`
> docs: update the version of the action used in the README example

- dist/post_run/index.js
- dist/run/index.js
- src/run.ts
The golangci-lint-action doesn't work when `only-new-issues: true` is specified, but the pull request was created from a private fork repository to a private repository.
See more why you would need pull_request_target for that: https://github.community/t/will-github-actions-support-pull-request-events-from-a-fork-to-a-private-base-repository/17471
The PR fixes this.
The action works perfectly with pull_request_target, but users should not forget to specify ref when running `actions/checkout`.
```
on: pull_request_target
[...]
- uses: actions/checkout@v3
with:
[.. other with params ..]
ref: "refs/pull/${{ github.event.number }}/head"
[...]
- name: golangci-lint
uses: golangci/golangci-lint-action@NEW_VERSION
with:
only-new-issues: true
[...]
```
> feat: add support for pull_request_target and only-new-issues

- README.md
- action.yml
- dist/post_run/index.js
- dist/run/index.js
- src/cache.ts
Add a separate `skip-save-cache` option that, when set to true, will avoid saving caches even if restoring caches are
enabled by other options.
This will allow caches to be utilized while preventing cache bloat in various situations, e.g. on Github merge queue
branches, which are essentially throwaway branches.
Resolves #641
> feat: add option to not save cache

- README.md
- action.yml
- dist/post_run/index.js
- dist/run/index.js
- src/cache.ts
Fixes #863
Fixes #807
Fixes #984
Fixes #703
> feat: remove Go cache management

- README.md
- dist/post_run/index.js
- dist/run/index.js
- src/run.ts
This PR adds support for `pull` and `merge_group` events with the option `only-new-issues`.
`merge_group` event demo: https://github.com/golangci/super-waffle/pull/1
Fixes #956
Fixes #531
Closes #520
> feat: support for `pull` and `merge_group` events with the option `only-new-issues`

- README.md
- dist/post_run/index.js
- dist/run/index.js
- src/run.ts
`compareCommits` is deprecated and replaced by `compareCommitsWithBasehead`.
`compareCommitsWithBasehead` allows usage of 2-dot compare syntax (only files content diff) instead of the 3-dot (commits and files).
> feat: uses 2 dots compare syntax for push diff

- README.md
- action.yml
- dist/post_run/index.js
- dist/run/index.js
- src/cache.ts
Adds new `cache-invalidation-interval` option.
Fixes #779
> feat: add option to control cache invalidation interval

- README.md
- action.yml
- dist/post_run/index.js
- dist/run/index.js
- problem-matchers.json
- src/run.ts
- remove the code inside the golangci-lint action that forces the output format to use `github-actions`
- remove the option `annotations` of this action because it's useless
- add an option to force adding the problem matchers of golangci-lint inside the action.
https://github.com/golangci/golangci-lint/issues/4695#issuecomment-2097087189
> feat: rewrite format handling

- dist/post_run/index.js
- dist/run/index.js
- src/run.ts
> fix: use 3-dots syntax for diff on push

- README.md
Related to #74
Related to https://github.com/golangci/golangci-lint/issues/828
> docs: add Go workspace examples

- README.md
- action.yml
- dist/post_run/index.js
- dist/run/index.js
- package-lock.json
- package.json
- src/install.ts
- src/run.ts
> feat: allow to skip golangci-lint installation

- README.md
PR updates the local development instructions in README.md that are currently causing errors since `npm run` doesn't contain `prepare-dips`.
Fixes #1124
> docs: update local development instructions

- README.md
This action can be executed without specifying a version.
I have confirmed in [action.yml](https://github.com/golangci/golangci-lint-action/blob/master/action.yml) and [version.ts](https://github.com/golangci/golangci-lint-action/blob/master/src/version.ts) that it is a working implementation even if it is not required.
> docs: update README options version from required to optional

- .github/workflows/test.yml
- action.yml
- dist/post_run/index.js
- dist/run/index.js
- src/run.ts
By detecting if a configuration file is present (or set with `--config=`), we can run the verification of the configuration file by default.
The verification can be disabled by setting `verify` to false.
> feat: verify with the JSONSchema by default

- README.md
From [this Issue](https://github.com/golangci/golangci-lint-action/issues/1202), we made [this PR](https://github.com/golangci/golangci-lint-action/pull/1203). We missed a line mentioning `checks` permissions
Change the line
> docs: fix checks permissions for annotations

- .github/workflows/test.yml
- .golangci.yml
- README.md
- action.yml
- dist/post_run/index.js
- dist/run/index.js
- go.mod
- sample-go-mod/.golangci.yml
- sample-go-mod/go.mod
- sample-go-mod/tools.go
- sample-go-tool/.golangci.yml
- sample-go-tool/go.mod
- src/install.ts
- src/run.ts
- src/version.ts
Until v2 is released, checks will fail.
> feat: golangci-lint v2 support

- README.md
I struggled a bit with setting the path to a config file until I realized that the path needs to be a full absolute path on disk when Github Actions runs it.  Using the `github.workspace` context variable seems to be the easiest solution.
Just thought I would document it to save someone else from the frustration.
> docs: add note about github.workspace

- README.md
> docs: upgrade checkout GitHub action to v5
